apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tasklane.worker.fullname" . }}
  labels:
    {{- include "tasklane.worker.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.worker.replicaCount }}
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      {{- include "tasklane.worker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.worker.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "tasklane.worker.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "tasklane.worker.fullname" . }}
      automountServiceAccountToken: false
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: 30
      securityContext:
        {{- include "tasklane.podSecurityContext" . | nindent 8 }}
      {{- with .Values.worker.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.worker.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: worker
          image: {{ include "tasklane.image" .Values.worker.image | quote }}
          imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
          ports:
            - name: metrics
              containerPort: {{ .Values.worker.metricsPort }}
          envFrom:
            - configMapRef:
                name: {{ include "tasklane.fullname" . }}-config
          volumeMounts:
            - name: db-secret
              mountPath: /etc/tasklane/db
              readOnly: true
          livenessProbe:
            httpGet:
              path: /healthz
              port: metrics
            periodSeconds: 15
            timeoutSeconds: 2
            failureThreshold: 4
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
          securityContext:
            {{- include "tasklane.containerSecurityContext" . | nindent 12 }}
      volumes:
        {{- include "tasklane.dbSecretVolume" . | nindent 8 }}
