{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "tasklane.fullname" . }}-default-deny
  labels:
    {{- include "tasklane.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes: [Ingress, Egress]
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "tasklane.fullname" . }}-allow-dns
  labels:
    {{- include "tasklane.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes: [Egress]
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "tasklane.api.fullname" . }}-allow-gateway
  labels:
    {{- include "tasklane.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "tasklane.api.selectorLabels" . | nindent 6 }}
  policyTypes: [Ingress]
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.networkPolicy.gatewayNamespace }}
      ports:
        - protocol: TCP
          port: 8080
{{- if .Values.postgresql.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "tasklane.postgres.fullname" . }}-allow-app
  labels:
    {{- include "tasklane.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "tasklane.postgres.selectorLabels" . | nindent 6 }}
  policyTypes: [Ingress]
  ingress:
    - from:
        - podSelector:
            matchLabels:
              {{- include "tasklane.api.selectorLabels" . | nindent 14 }}
        - podSelector:
            matchLabels:
              {{- include "tasklane.worker.selectorLabels" . | nindent 14 }}
      ports:
        - protocol: TCP
          port: 5432
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "tasklane.fullname" . }}-allow-egress-postgres
  labels:
    {{- include "tasklane.labels" . | nindent 4 }}
spec:
  podSelector:
    matchExpressions:
      - key: app.kubernetes.io/component
        operator: In
        values: [api, worker]
      - key: app.kubernetes.io/instance
        operator: In
        values: [{{ .Release.Name }}]
  policyTypes: [Egress]
  egress:
    - to:
        - podSelector:
            matchLabels:
              {{- include "tasklane.postgres.selectorLabels" . | nindent 14 }}
      ports:
        - protocol: TCP
          port: 5432
{{- end }}
{{- end }}
